apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-101-front-proxy
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  envoy.yaml: |
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address: { address: 0.0.0.0, port_value: 8001 }
    stats_flush_interval:
      seconds: 5
    static_resources:
      listeners:
      - name: app
        address:
          socket_address: { address: 0.0.0.0, port_value: 8080 }
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: HTTP1
              stat_prefix: front_proxy
              route_config:
                name: app
                virtual_hosts:
                - name: apps
                  domains: [ "*" ]
                  routes:
                  - match: { prefix: "/flask_app/" }
                    route: { prefix_rewrite: "/", cluster: flask_app }
                    decorator: { operation: decorator_flask_app }
                  - match: { prefix: "/flask_app" }
                    route: { prefix_rewrite: "/", cluster: flask_app }
                    decorator: { operation: decorator_flask_app }

                  - match: { prefix: "/flask_app_admin" }
                    route: { cluster: flask_app_admin }
                    decorator: { operation: decorator_flask_app_admin }

                  - match: { prefix: "/front_proxy_admin" }
                    route: { prefix_rewrite: "/admin", cluster: front_proxy_admin }
                    decorator: { operation: decorator_flask_app_admin }
                  - match: { prefix: "/front_proxy_admin/" }
                    route: { prefix_rewrite: "/admin", cluster: front_proxy_admin }
                    decorator: { operation: decorator_flask_app_admin }

                  require_tls: NONE
              http_filters:
              - name: envoy.router
                config: {}
              server_name: front_proxy_app
              generate_request_id: true
      clusters:
      - name: flask_app
        type: STRICT_DNS
        connect_timeout: 10s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address: { address: envoy-101-flask-app, port_value: 8080 }

      - name: flask_app_admin
        type: STRICT_DNS
        connect_timeout: 10s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address: { address: envoy-101-flask-app, port_value: 8001 }

      - name: front_proxy_admin
        type: STRICT_DNS
        connect_timeout: 10s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address: { address: 0.0.0.0, port_value: 8001 }
