---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: envoy-101-front-proxy
  labels:
    app: envoy-101-front-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-101-front-proxy
  template:
    metadata:
      name: envoy-101-front-proxy
      labels:
        app: envoy-101-front-proxy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:v1.8.0
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.yaml"
            - "--mode serve"
            - "--v2-config-only"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-101-front-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-101-front-proxy
  labels:
    app: envoy-101-front-proxy
spec:
  type: NodePort
  selector:
    app: envoy-101-front-proxy
  ports:
    - name: all-traffic
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 31012
    - name: admin
      port: 81
      protocol: TCP
      targetPort: 8001
      nodePort: 31013
