---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paytm-deploy-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paytm-app
      version: "v2"
  template:
    metadata:
      labels:
        app: paytm-app
        version: "v2"
    spec:
      containers:
      - name: paytm
        image: hashicorp/http-echo:0.2.3
        args: ["-listen", ":8080", "-text", "Reply from paytm's v2"]
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: paytm-svc
  labels:
    app: paytm-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: paytm-app
---
